sudo : required
services:
    - docker

before_install:
    - docker build -t test -f ./client/Dockerfile.dev ./client

script:
    - docker run test npm test -- --coverage

after_success:
    - docker build -t m_client ./client
    - docker build -t m_server ./server
    - docker build -t m_nginx ./nginx
    - docker build -t m_worker ./worker
    #Log in to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push m_client
    - docker push m_server
    - docker push m_nginx
    - docker push m_worker

   